# Use the official Ubuntu base image
FROM armswdev/tensorflow-arm-neoverse:r23.07-tf-2.12.0-eigen

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements_ARM.txt /app/

# Upgrade pip and install dependencies 
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements_ARM.txt
RUN pip3 install tensorflow-addons --verbose

# Copy the rest of the project 

COPY . /app/

# Expose the port Django runs on 
EXPOSE 8000

# Run migrations and start the sever 
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]


